#!/usr/bin/env bash
# This script displays a list of currently running processes.
# Must show all processes, for all users, including those which might not have a TTY.
# Display a user-oriented format.
# Show process hierarchy.

ps -a -x -u -f
